# =============================================================================
# configs/base/base_config.yaml - 基础配置模板
# =============================================================================

# 这是整个配置系统的"基因模板"，定义了所有实验的基本结构
# 其他所有配置都可以继承和扩展这个基础配置

# 实验元信息 - 每个实验都应该有清晰的身份标识
experiment_name: "base_experiment"
description: "Base configuration template for all experiments"
version: "1.0.0"
tags: ["baseline", "template"]

# 随机种子设置 - 确保实验的可重现性
seed: 3407

# 日志级别设置
log_level: "INFO"

# 模型配置框架 - 这是一个抽象模板，具体实验会覆盖这部分
model:
  target: null  # 具体的模型类路径，由子配置指定
  params: {}    # 模型参数，由子配置指定

# 数据配置框架 - 定义数据处理的标准接口
data:
  target: null  # 数据模块类路径，由子配置指定
  params:
    # 通用数据参数
    batch_size: 32
    num_workers: 4
    pin_memory: true
    # 具体参数由子配置添加

# 训练器配置框架 - PyTorch Lightning Trainer的配置
trainer:
  target: pytorch_lightning.Trainer
  params:
    # 基础训练配置
    max_epochs: 100
    accelerator: auto    # 自动检测GPU/CPU
    devices: auto        # 自动检测设备数量
    precision: 32        # 数值精度
    
    # 验证配置
    val_check_interval: 1.0
    check_val_every_n_epoch: 1
    
    # 梯度配置
    gradient_clip_val: 1.0
    accumulate_grad_batches: 1
    
    # 其他训练配置
    enable_progress_bar: true
    enable_model_summary: true
    deterministic: false  # 设为true可提高重现性，但会降低性能

# 回调函数配置 - 定义训练过程中的监控和保存策略
callbacks:
  # 模型检查点保存
  model_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: "outputs/checkpoints"
      filename: "best-{epoch}-{val_f1:.4f}"
      monitor: "val_f1"
      mode: "max"
      save_top_k: 3
      save_last: true
      auto_insert_metric_name: false
  
  # 早停策略
  early_stopping:
    target: pytorch_lightning.callbacks.EarlyStopping
    params:
      monitor: "val_f1"
      mode: "max"
      patience: 15
      min_delta: 0.001
      verbose: true
  
  # 学习率监控
  lr_monitor:
    target: pytorch_lightning.callbacks.LearningRateMonitor
    params:
      logging_interval: "step"

# 日志记录器配置 - 定义实验追踪和可视化
loggers:
  # TensorBoard日志
  tensorboard:
    target: pytorch_lightning.loggers.TensorBoardLogger
    params:
      save_dir: "outputs/logs"
      name: "tensorboard"
      version: null  # 自动生成版本号

# 输出目录配置 - 定义各种输出文件的保存位置
outputs:
  checkpoint_dir: "outputs/checkpoints"
  log_dir: "outputs/logs"
  predictions_dir: "outputs/predictions"
  figures_dir: "outputs/figures"

# 计算资源配置 - 硬件相关设置
compute:
  # GPU设置
  gpu_ids: [0]           # 使用的GPU ID列表
  mixed_precision: false # 是否使用混合精度训练
  
  # 内存优化
  find_unused_parameters: false
  sync_batchnorm: false